<?php
$sql ="SELECT FORMAT(-SUM(value_usd_total),4) AS amount FROM bs_transfers WHERE date = '$date_for_sql' AND supplier_id ='1'";
$rst = $dbc->Query($sql);
$line_standard = $dbc->Fetch($rst);

$sql ="SELECT FORMAT(-SUM(value_usd_total),4) AS amount FROM bs_transfers WHERE date = '$date_for_sql' AND supplier_id ='1'";
$rst = $dbc->Query($sql);
$line_standardUse = $dbc->Fetch($rst);

$sql ="SELECT FORMAT(-SUM(value_usd_total),4) AS amount FROM bs_transfers WHERE date = '$date_for_sql' AND supplier_id ='18'";
$rst = $dbc->Query($sql);
$line_jinsung = $dbc->Fetch($rst);

$sql ="SELECT FORMAT(-SUM(value_usd_total),4) AS amount FROM bs_transfers WHERE date = '$date_for_sql' AND supplier_id ='17'";
$rst = $dbc->Query($sql);
$line_goldlin = $dbc->Fetch($rst);

    
    echo '<div class="mb-3">';
        echo '<table class="table table-sm table-bordered">';
            echo '<thead>';
                echo '<tr>';
                    echo '<th class="text-center"></th>';
                    echo '<th class="text-center"></th>';
                    echo '<th class="text-center">B/F</th>';
                    echo '<th class="text-center">LC</th>';
                    echo '<th class="text-center">Interest</th>';
                    echo '<th class="text-center">Charges</th>';
                    echo '<th class="text-center">Gain (Loss) From Trade</th>';
                    echo '<th class="text-center">Deposit</th>';
                    echo '<th class="text-center">Add</th>';
                    echo '<th class="text-center">Used Today</th>';
                    echo '<th class="text-center">Others</th>';
                    echo '<th class="text-center">Deduct Deferred Stock Mkt Value</th>';
                    echo '<th class="text-center">C/F</th>';
                echo '</tr>';
            echo '</thead>';
            echo '<tbody>';
                echo '<tr>';
                    echo '<th class="text-left">Require FX before deduct deposit</th>';
                    echo '<th class="text-left"></th>';
                    echo '<td class="text-right"></td>';
                echo '</tr>';
                echo '<tr>';
                echo '<th class="text-left">Outstanding USD / Deposit</th>';
                    echo '<th class="text-left"></th>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                echo '</tr>';
                echo '<tr>';
                    echo '<th class="text-left"></th>';
                    echo '<th class="text-left">WF</th>';
                    echo '<td class="text-right">-</td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right">-</td>';
                echo '</tr>';
                echo '<tr>';
                    echo '<th class="text-left"></th>';
                    echo '<th class="text-left">StoneX (Physical) INTL</th>';
                    echo '<td class="text-right">'.number_format(0,2).'</td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right">'.number_format(0,2).'</td>';
                echo '</tr>';
                echo '<tr>';
                    echo '<th class="text-left"></th>';
                    echo '<th class="text-left">StoneX (Fund in) (Defer)</th>';
                    echo '<td class="text-right">-</td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right">-</td>';
                echo '</tr>';
                echo '<tr>';
                    echo '<th class="text-left"></th>';
                    echo '<th class="text-left">HERAEUS</th>';
                    echo '<td class="text-right">-</td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right">-</td>';
                echo '</tr>'; 
                echo '<tr>';
                    echo '<th class="text-left"></th>';
                    echo '<th class="text-left">Local Bar</th>';
                    echo '<td class="text-right">-</td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right">-</td>';
                echo '</tr>';  
                echo '<tr>';
                    echo '<th class="text-left"></th>';
                    echo '<th class="text-left">MKS HONGKONG</th>';
                    echo '<td class="text-right">'.number_format(814.60,2).'</td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right">'.number_format(814.60,2).'</td>';
                echo '</tr>';
                echo '<tr>';
                    echo '<th class="text-left"></th>';
                    echo '<th class="text-left">Gold Linkage</th>';
                    echo '<td class="text-right">-</td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right">'.$line_goldlin['amount'].'</td>';
                    echo '<td class="text-right">'.$line_goldlin['amount'].'</td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right">-</td>';
                echo '</tr>';  
                echo '<tr>';
                    echo '<th class="text-left"></th>';
                    echo '<th class="text-left">Samsung</th>';
                    echo '<td class="text-right">'.number_format(0.35,2).'</td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right">'.number_format(0.35,2).'</td>';
                echo '</tr>';
                echo '<tr>';
                    echo '<th class="text-left"></th>';
                    echo '<th class="text-left">STD (STBLC)</th>';
                    echo '<td class="text-right">'.number_format(730000,2).'</td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right text-danger">'.number_format(730000,2).'</td>';
                echo '</tr>';
                echo '<tr>';
                    echo '<th class="text-left"></th>';
                    echo '<th class="text-left">STD (Physical) (เงินเกินที่ STD.)</th>';
                    echo '<td class="text-right">'.number_format(1103122.07,2).'</td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right">'.$line_standard['amount'].'</td>';
                    echo '<td class="text-right">'.$line_standardUse['amount'].'</td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right text-danger">'.number_format(1103122.07,2).'</td>';
                echo '</tr>';    
               
                echo '<tr>';
                    echo '<th class="text-left"></th>';
                    echo '<th class="text-left">JINSUNG</th>';
                    echo '<td class="text-right">-</td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right">'.$line_jinsung['amount'].'</td>';
                    echo '<td class="text-right">'.$line_jinsung['amount'].'</td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right"></td>';
                    echo '<td class="text-right">-</td>';
                echo '</tr>';                                
            echo '</tbody>';
        echo '</table>';
    echo '</div>';
