var production_pmr = {
	pmr: {
		dialog_lookup: fn.noaccess,
		dialog_add: fn.noaccess,
		dialog_prepare: fn.noaccess,
		dialog_edit: fn.noaccess,
		dialog_remove: fn.noaccess,
		dialog_approve: fn.noaccess,
		add: fn.noaccess,
		edit: fn.noaccess,
		remove: fn.noaccess,
		prepare: fn.noaccess,
		approve: fn.noaccess,
		select: fn.noaccess,
	}, recycle: {
		dialog_lookup: fn.noaccess,
		dialog_add: fn.noaccess,
		dialog_prepare: fn.noaccess,
		dialog_edit: fn.noaccess,
		dialog_remove: fn.noaccess,
		dialog_approve: fn.noaccess,
		add: fn.noaccess,
		edit: fn.noaccess,
		remove: fn.noaccess,
		prepare: fn.noaccess,
		approve: fn.noaccess,
		select: fn.noaccess,
	},
	in: {
		dialog_lookup: fn.noaccess,
		dialog_add: fn.noaccess,
		dialog_prepare: fn.noaccess,
		dialog_edit: fn.noaccess,
		dialog_remove: fn.noaccess,
		dialog_approve: fn.noaccess,
		add: fn.noaccess,
		edit: fn.noaccess,
		remove: fn.noaccess,
		prepare: fn.noaccess,
		approve: fn.noaccess,
		select: fn.noaccess,
	},
	out: {
		dialog_lookup: fn.noaccess,
		dialog_add: fn.noaccess,
		dialog_prepare: fn.noaccess,
		dialog_edit: fn.noaccess,
		dialog_remove: fn.noaccess,
		dialog_approve: fn.noaccess,
		add: fn.noaccess,
		edit: fn.noaccess,
		remove: fn.noaccess,
		prepare: fn.noaccess,
		approve: fn.noaccess,
		select: fn.noaccess,
	}
};
$.extend(fn.app, { production_pmr: production_pmr });
